### ISSUE TITLE
Automatic JSX runtime

### ISSUE THREAD

**Issue by hanford** [mwood23/slate-test-utils#1]
Hello, thanks for coming up with this clever solution. Testing w/ Slate is critical yet very much unsolved, or at least it was until this came out! Where I work, we've been using Cypress w/ several hacks in place to test Slate. This is much faster, neater abstraction.

I was wondering if you had any idea how to enable the `jsx` extensions with an already set `importSource` using the automatic JSX runtime.

We're using Emotion, which requires us to set the pragma importSource to `@emotion/react`.

It would be so awesome if we could use the JSX using what's described in this packages README in addition to Emotion.

I'm not blocked, I can just _not_ use JSX syntax and instead use the function exported from `slate-hyperscript`:

```jsx
    jsx('editor', {}, [
      jsx('element', { type: 'paragraph' }, [
        jsx('text', ['potato']),
        jsx('text', { bold: true }, [' cucumbers', jsx('cursor')]),
      ]),
    ]),
```

Feel free to close this issue if it's off topic or you're not sure what the solution would look like.

Thanks again for creating and open sourcing this package!

**Comment by mwood23** [comment]
Hey @hanford, I've ran into this a couple times on a previous project. Unfortunately I don't have a good solution beyond using separate files. For example, you can write the JSX hyperscript in one file and then import it into another file which is using a different pragma. If you create a small repo I can clone down I'm happy to give it a look if that's not helpful.
