### ISSUE TITLE
Upgrade slate and slate-react version

### ISSUE THREAD

**Issue by andres-vidal** [mwood23/slate-test-utils#5]
Hello! First of all, congratulations and thank you very much for this utility. The library looks really promising for writing meaningful test easily, specially when compared with the alternatives.

Opening this issue because it would be nice to keep the `slate` and `slate-react` dependencies versions updated. I skimmed through the code and Slate's changelog and since `0.70.0` (current dependency version) there doesn't seem to be any critical changes for this library. Might be useful to use hyphen ranges `0.70.0-0.72.x` to keep supporting at least the most recent patch on current minor version.

Thanks again for open sourcing this!

**Comment by mwood23** [comment]
Good idea, this should be pretty flexible to work with most code moving forward in Slate so I'll update to be `>=` on the next release. I don't want to resort to hyphen ranges until they introduce a change that would be breaking to this library.

**Comment by mwood23** [comment]
Released in 1.2.1.
